name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Production Build Check
      id: production-build-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Production Build Check
        setup-command: npm install
        command: npm run build
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRODUCTION-BUILD-CHECK_RESULTS: "${{steps.production-build-check.outputs.result}}"
      with:
        runners: production-build-check
